language: php
dist: bionic
php:
  - 7.4.0
  - 7.4.1
  - 7.4
matrix:
  include:
    - php: 7.4
      env:
        - xdebug=yes
    - php: 7.4
      env:
        - psalm=yes
  fast_finish: true
cache:
  files:
    - ./phpunit.cache
    - ./.php_cs.cache
  directories:
    - $HOME/.composer/cache
    - ./psalm/cache
before_script:
  - if [[ "$xdebug" != "yes" || "$psalm" = "yes" ]]; then phpenv config-rm xdebug.ini; fi
install:
  - travis_retry composer install --no-interaction --no-suggest --prefer-dist
script:
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/phpunit --coverage-clover=./phpunit.clover && ./vendor/bin/php-coveralls --no-interaction -vvv; else ./vendor/bin/phpunit --no-coverage; fi
  - if [[ "$xdebug" = "yes" ]]; then ./vendor/bin/infection --min-msi=100; fi
  - if [[ "$psalm" = "yes" ]]; then ./vendor/bin/psalm --shepherd --show-info=false --diff --diff-methods --threads=2; fi
  - if [[ "$xdebug" != "yes" ]]; then composer run static-analysis; fi
after_script:
  - if [[ "$xdebug" = "yes" ]]; then cat infection.log; fi
